### ISSUE TITLE
test_pack_C_OpenSession_Call in keehive/src/generated/test/test_pack.c fails

### ISSUE THREAD

**Issue by gijzelaerr** [arpa2/keehive#2]
the first `der_unpack()` call inside `unpack_C_OpenSession_Call()` on the packed structure fails. I don't understand what is wrong, as far as I know, I set & pack all the fields correctly.

**Comment by gijzelaerr** [comment]
We need to pack the flags in a BIT STRING. Helper functions are implemented in this quick-der branch

https://github.com/vanrein/quick-der/tree/keehub

But there are no helpers for a `CK_FLAGS` (`CK_ULONG` / `unsigned long`) type.

**Comment by gijzelaerr** [comment]
Also the API is inconsistent. for other types, like `der_put_int32` and `der_put_bool`, a pointer to a buffer is supplied and a cursor is returned. In the current implementation, a der_buf_bitstring dercursor argument is expected and an error code is returned.

**Comment by vanrein** [comment]
The API is optimised (and designed) per function, that is true.

The reason why the flags don't relate directly is the different nature of the representation in the API and in DER.  Please load 4 bytes, setting the default value to 0 and ignoring any out-of-range errors for each of the bytes and combine them into the ULONG.  Lower-numbered bits/bytes are MSB.

DER stores BIT STRINGS in sequences of bytes, not long words.  When extending, this is done at the end, by adding bytes.  It is not very logical to link this to uint32_t when you don't know (in general) whether there will always be just 16 bits, for instance.

**Comment by gijzelaerr** [comment]
implemented per https://github.com/arpa2/keehive/commit/8a8a5d360caaa74859ee966aeeddb3dd728c69a7

**Comment by gijzelaerr** [comment]
this issue has been resolved.
