### ISSUE TITLE
der_putget_CK_BYTE_ARRAY in src/static/test/test_derputget.c fails

### ISSUE THREAD

**Issue by gijzelaerr** [arpa2/keehive#3]
This test just does a pack and unpack roundtrip for a CK_BYTE_ARRAY. Somehow the even characters are missing. (input: `"abcdefghijklm"` output `"acegikm"`).

**Comment by vanrein** [comment]
Veel eigen code zo te zien, dus ik wacht tot je expliciet om mijn hulp vraagt.  Het is altijd handig om buffers te dumpen op plekken waar je weet wat ze zouden moeten zijn.  Ook de waarde tussen pack/unpack is handig te bekijken als 1e split.

**Comment by gijzelaerr** [comment]
@vanrein maybe useful if you have a quick look? experiencing the same problem now with another unpacker. When I manually dump and unpack the der structure there seem to be 13 elements, so I'm quite sure I'm using the iterator wrongly or some other detail?

https://github.com/arpa2/keehive/blob/master/src/static/test/test_derputget.c#L39

**Comment by gijzelaerr** [comment]
Maybe this is related to the changed behavior of `der_unpack()` where it modifies the iterator?

**Comment by gijzelaerr** [comment]
yeah, if I copy the iterator it works again.

**Comment by gijzelaerr** [comment]
https://github.com/vanrein/quick-der/issues/67
