### ISSUE TITLE
C_VerifyRecoverInit mssing in ASN1 definition

### ISSUE THREAD

**Issue by gijzelaerr** [arpa2/keehive#4]
is defined in the standard

http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html

but missing in the ASN1 definition. Call and Return for C-VerifyRecover are defined though.

**Comment by vanrein** [comment]
Thanks, fixed in abcddf8b23124b5832e79d649f99ebfac6a5d0af
